### ISSUE TITLE
Bug: Error Codes not removed

### ISSUE THREAD

**Issue by joshgenat** [alborzdev/2311-Project#13]
## Name
Program’s live error messages are not removed after resolving issues

## Description
When producing an error in the text tab, an error message will pop up accordingly. However, when fixing the error the error message displayed on the right still remains, seeming like there is still an error with the tab.

## Steps to Reproduce
1. Run the program, paste the supplied tab (or any other tab), 
2. Type another letter or word that will disrupt the usual text tab format
3. The program will then display an error message.
4. Delete that letter/word to revert back to it's original tab
5. Note that the error message is still displayed on the right side of the screen

## Expected Result
When being shown a live error message, resolving the error should remove that error message and clear the screen without any mistakes. 

## Actual Result
When being shown a live error message, resolving the error does not remove that error message. Seeming like the error still remains, thus confusing the user when inputting the tab.

## Priority
Medium

## Status 
Ready for Development

## Screenshot
Adding the letter 'a' causing a live error message to pop up:
![image](https://user-images.githubusercontent.com/77293319/112188967-e456f400-8bd9-11eb-9956-c694dcb39fd4.png)

After fixing: (error message still there)

![image](https://user-images.githubusercontent.com/77293319/112189014-f33da680-8bd9-11eb-885c-f5d02d4e6d09.png)

**Comment by lianattily** [comment]
fixed!
