### ISSUE TITLE
Bug: Sheet Music Formatting

### ISSUE THREAD

**Issue by joshgenat** [alborzdev/2311-Project#14]
## Name
Program’s sheet music converter not formatted properly

## Description
After selecting “convert to sheet music”, the sheet music file has all the notes in a single spot. The notes are not in it's proper locations, instead bundled into one spot.

## Steps to Reproduce
1. Run the program
2. Paste the supplied tab, then select the option “convert to sheet music”
3. Once converted and downloaded, go to https://opensheetmusicdisplay.github.io/demo/ to display the sheet music.
4. Note the sheet music has notes bunched up together

## Expected Result
Running the program choosing the "convert to sheet music" option selected will accurately display the sheet music.

## Actual Result
Running the program choosing the convert to sheet music option selected has all the notes bundled in one spot. Notes are not where it was supposed to be.

## Priority
High

## Status 
Ready for Development

## Input Used
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

## Screenshot
![image](https://user-images.githubusercontent.com/77293319/112189868-d48bdf80-8bda-11eb-9ee7-33a1b415b607.png)
![image](https://user-images.githubusercontent.com/77293319/112189884-d81f6680-8bda-11eb-9c94-5e59f00e1147.png)

**Comment by lianattily** [comment]
fixed!
