### ISSUE TITLE
Bug: Error Message Pop-Up

### ISSUE THREAD

**Issue by joshgenat** [alborzdev/2311-Project#15]
## Name
Program’s Error Message not always Popping up

## Description
After exporting a text tab with an error, a pop-up shows that you cannot export the file as it has an error. However, this does not always appear for every error. The live error message on the right still appears, however the pop-up error message does not appear accordingly.

## Steps to Reproduce
1. Run the program, paste the supplied tab, then export.
2. An error pop-up message will show it did not work. 
3. Now paste another supplied tab with a different kind of error
4. Select export and no error message will pop up.

## Expected Result
Running the program with an error will prevent the user from converting to XML, displaying a message that indicates the error. Displaying a pop-up error should prevent the user from being able to export the tab. This should pop up every time there is an error with the code

## Actual Result
Running the program with an error does not display a message that informs the user it was unable to export successfully. A live-error message on the right appears, but no pop-up error message that prevents the user from exporting

## Priority
Medium

## Status 
Ready for Development

## Input Used
First Image:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0-------------|---0---------------|

Second Image:

|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0-------------a---0---------------|

## Screenshot
![image](https://user-images.githubusercontent.com/77293319/112190094-0e5ce600-8bdb-11eb-9cb1-348dde778113.png)

Different Error, new error message displayed on the right, but no pop-up error message: 

![image](https://user-images.githubusercontent.com/77293319/112190116-1452c700-8bdb-11eb-8bcb-c60679693064.png)

**Comment by lianattily** [comment]
works now!
