### ISSUE TITLE
Bug: Does not recognize double digits frets

### ISSUE THREAD

**Issue by Hua-Kevin** [alborzdev/2311-Project#16]
Reporter: Kevin Hua
Email: kevhua36@my.yorku.ca
Version: 6fb4d43
Platform: Windows 10

Name
The program cannot recognize double digits frets

Description 
After importing a guitar tablature that contains a note in the double-digit fret, it sends an error.

Expected result
Correctly detect tablature and translate it correctly

Actual result
The program wrongly detects an error reporting that the length in the line is incorrect.

Priority
Low

Status
Ready for development.

Screenshot
![double digits fret](https://user-images.githubusercontent.com/42554604/112250851-87d2f380-8c30-11eb-8391-b68af8c19320.JPG)

**Comment by lianattily** [comment]
fixed!
