### ISSUE TITLE
Bug: Irregular text format when on TextArea after uploading a txt file

### ISSUE THREAD

**Issue by Kumar-Venkatessh-216693764** [alborzdev/2311-Project#22]
Reporter: Venkatessh Kumar

Email: venki365@my.yorku.ca

Issue Title: The tablature text in the TextArea is irregularly formatted and hard to read. No resizing feature included.

Version: TabT2MXL March 24 2021 Master, Java-15 as stated in User Manual

Platform: MacOS Version 10.13.6

Steps to Reproduce:

-Upload a file containing a tablature.
-Check the TextArea
-There is also no resizing option for the app which is a downside to not being able to increase the size of the app screen to accommodate big texts.

Expected:
The text fits perfectly into the TextArea just like the text in uploaded file.

Actual:
The text is cramped up and hard to understand. The inability to resize the screen to fix this issue is also not added.

Priority: Medium - This bug is focused around User Experience, and seems to be easy to encounter. The User would be unable to make changes to the TextArea easily as it is hard to comprehend the tablature.

Severity: Medium- This bug is not severe and does not cause any issues apart from the unpleasant User Interaction of the app. 

Content of uploaded file:
e|-----0-------------------0-----0----------------0-------0-------------------3p0-------0---|
B|--3-----3--1-------1--------3-----3--1------1-----3--3----3--1-------1----1------1h3--1---|
G|--------------0h2--2--2----------------0h2----2-----------------0h2--2--2-----------------|
D|-------------------3-------------------------------------------------3--------------------|
A|--------------------------------------------0-----------------------------------------0---|
E|----------------------------3---------------------3--3---------------------------3--------|

e|-----0-------------------0-----0----------------0--------0-------------------3p0-------0--|
B|--3-----3--1-------1--------3-----3--1------1------3--3----3--1-------1----1------1h3--1--|
G|--------------0h2--2--2----------------0h2----2------------------0h2--2--2----------------|
D|-------------------3--------------------------------------------------3-------------------|
A|--------------------------------------------0------------------------------------------0--|
E|--3-------------------------3----------------------3--3---------------------------3-------|

Screenshots:

First page when the app is run:
<img width="1375" alt="Screen Shot 2021-03-24 at 5 12 50 PM" src="https://user-images.githubusercontent.com/46407886/112319385-725cd880-8cc7-11eb-9898-715b14426696.png">

Uploading a file to the app:
<img width="1375" alt="Screen Shot 2021-03-24 at 5 13 00 PM" src="https://user-images.githubusercontent.com/46407886/112319612-b059fc80-8cc7-11eb-82aa-057d1f374693.png">

Contents of the file:
<img width="829" alt="Screen Shot 2021-03-24 at 5 38 33 PM" src="https://user-images.githubusercontent.com/46407886/112319725-c8318080-8cc7-11eb-96d1-1fbb28da9e14.png">

Display of the contents in the TextArea:
<img width="1375" alt="Screen Shot 2021-03-24 at 5 13 09 PM" src="https://user-images.githubusercontent.com/46407886/112319810-dd0e1400-8cc7-11eb-822b-a28f95ce6c2e.png">

**Comment by lianattily** [comment]
fixed text area wrapping issue.
