### ISSUE TITLE
Bug: Random sentences in the TextArea does not raise errors

### ISSUE THREAD

**Issue by Kumar-Venkatessh-216693764** [alborzdev/2311-Project#25]
Reporter: Venkatessh Kumar

Email: venki365@my.yorku.ca

Issue Title: Random sentences in the TextArea does not raise errors. When the errors are raised, you are still able to click on the export button with no error prompt.

Version: TabT2MXL March 24 2021 Master, Java-15 as stated in User Manual

Platform: MacOS Version 10.13.6

Steps to Reproduce:

Issue 1:-
-Write various sentences on the TextArea
-Click on "Export"
-Choose the name of the file and location to be exported to.
-Check for Error Prompts.

Issue 2:-
-After writing down random sentences on the TextArea, upload a text file containing a tablature.
-Errors are shown.
-Click "Export"
-Choose the name of the file and location to be exported to.

Expected:
Error prompts should be raised when trying to export an invalid tablature in the TextArea. The User should not be allowed to export an invalid tablature.

Actual:
For issue 1, no errors are displayed to the User and the User is allowed to export the random sentence. Although no file is saved to computer after the export process, there should be an error pop-up that prevents the user from doing this process in the first place.
For issue 2, although there are issues that are displayed on the side, the User is still allowed to perform the Export action with no file being saved to the computer.

Priority: Medium - This bug does not crash the program or disrupt the proper usage of the app, hence it is not highly prioritized. Some Users may encounter this problem if they have a slight error in their tablature and it is not displayed to user as an error.

Severity: Medium- The bug can cause the User to be confused on what went wrong (when they are not able to find the exported MusicXML file on their computer) since they were not specified on what exactly the issue was with their tablature, nor were they told the export action failed.

Screenshots:

First page when the app is run:
<img width="1375" alt="Screen Shot 2021-03-24 at 6 04 25 PM" src="https://user-images.githubusercontent.com/46407886/112331007-fd42d080-8cd1-11eb-9358-7a8cf9988365.png">

Write a random sentence in the TextArea:
<img width="1375" alt="Screen Shot 2021-03-24 at 6 37 02 PM" src="https://user-images.githubusercontent.com/46407886/112331113-10ee3700-8cd2-11eb-87ae-4a162e877a59.png">

Trying to export with the random sentence in the TextArea:
<img width="1375" alt="Screen Shot 2021-03-24 at 6 37 16 PM" src="https://user-images.githubusercontent.com/46407886/112331385-4c890100-8cd2-11eb-9bad-7444006f2c07.png">

App screen after exporting (No errors displayed of failed export action):
<img width="1375" alt="Screen Shot 2021-03-24 at 6 37 23 PM" src="https://user-images.githubusercontent.com/46407886/112331508-675b7580-8cd2-11eb-8d04-2bb372a1f198.png">

Proof the export action failed and no file was exported to my computer:
![Screen Shot 2021-03-24 at 6 55 17 PM](https://user-images.githubusercontent.com/46407886/112331645-89ed8e80-8cd2-11eb-8d18-01282d0335a9.png)

When adding a proper Tab file to the existing TextArea:
<img width="1375" alt="Screen Shot 2021-03-24 at 6 38 01 PM" src="https://user-images.githubusercontent.com/46407886/112332383-20ba4b00-8cd3-11eb-954c-8c38eeeb6144.png">

Click Export:
<img width="1375" alt="Screen Shot 2021-03-24 at 6 38 22 PM" src="https://user-images.githubusercontent.com/46407886/112332433-2b74e000-8cd3-11eb-8796-59b48fa7f788.png">

Screen after export (No errors specified on the export action failing):
![Screen Shot 2021-03-24 at 6 38 01 PM](https://user-images.githubusercontent.com/46407886/112332555-45aebe00-8cd3-11eb-806e-491e14d15cd0.png)

**Comment by lianattily** [comment]
The software must ignore accidental typos like extra random texts and still be able to export a valid XML file if the input itself is a valid tab
