### ISSUE TITLE
Issue with Error Message

### ISSUE THREAD

**Issue by Nicolae-Semionov** [alborzdev/2311-Project#27]
## Issue with Error Message

Raised by: Nicolae Semionov, 216468498

commit: 6fb4d43

## Description
This issue was identified when testing how the program handles bad inputs. The program correctly identified the problematic edit, and lets the user know of the location. However once fixed, the message does not go away which can be confusing to the user.

## Input & Result
Before bad edit:
![correct](https://user-images.githubusercontent.com/46364601/112349464-21d18500-8c9f-11eb-8b79-de16e00af66d.PNG)

Bad input created:
![bad](https://user-images.githubusercontent.com/46364601/112349722-580f0480-8c9f-11eb-8d53-1559945351d1.PNG)

Input resolved but error message persists
![resolved](https://user-images.githubusercontent.com/46364601/112349861-770d9680-8c9f-11eb-8515-adff7728ac5c.PNG)

Priority: Low
This issue is not very important. The error message can confuse the user as to why their tab still has errors after they tried to fix it, when in reality its just the error message not updating.

**Comment by lianattily** [comment]
fixed
