### ISSUE TITLE
Bad Formatting Issue Remains After Formatting Corrected

### ISSUE THREAD

**Issue by PBaciu** [alborzdev/2311-Project#28]
Reporter: Patrick Alexander Baciu
Email: baciupat@my.yorku.ca
Platform: Windows 10

Name:
Bad Formatting Issue Remains After Formatting Corrected

Description:
After modifying the tab to be of incorrect format and correcting the issue, the warning message remains.

Steps to Produce:
Start the application.
Paste in this sample guitar tab.
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|
Modify the tab to be of incorrect format [screenshot1] (note there is an error message)
Correct tab to be of correct format [screenshot2] (note that there is still an error message)
(Save changes button does not have an effect on this issue)

Expected result:
Error message disappears when tab is corrected.

Actual Result:
Error message remains when tab is corrected.

Input Used:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

Priority:
Low

Status:
Ready for development

Screenshots:
![image](https://user-images.githubusercontent.com/77293069/112355443-04eb8080-8ca4-11eb-863c-d84b68209d53.png)
![image](https://user-images.githubusercontent.com/77293069/112355513-1df43180-8ca4-11eb-96e1-bb616033e68a.png)

**Comment by lianattily** [comment]
fixed
