### ISSUE TITLE
Text Editor Constantly Highlighting Invalid Lines While Trying To Edit

### ISSUE THREAD

**Issue by PBaciu** [alborzdev/2311-Project#29]
Reporter: Patrick Alexander Baciu
Email: baciupat@my.yorku.ca
Platform: Windows 10

Name:
Bad Formatting Issue Remains After Formatting Corrected

Description:
After modifying the tab to be of incorrect format and correcting the issue, the warning message remains.

Steps to Produce:
Start the application.
Paste in this sample guitar tab.
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

Try modifying the tab to this format. It's quite difficult due to other lines being highlighted! [screenshot1]
|-----------0h1---|-0---------------|  
|---------0-------|-0---------------|  
|-------1-------1-|-1---------------|    
|-----2-----------|-2---------------|  
|---2-------------|-2---------------|  
|-0---------------|-0---------------|

Expected result:
Text editing is easy to use.

Actual Result:
Text editor constantly fully selects other lines and makes editing difficult.

Input Used:
|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

Priority:
Low

Status:
Ready for development

Screenshots:
![image](https://user-images.githubusercontent.com/77293069/112356413-f81b5c80-8ca4-11eb-919f-8a9367e119f7.png)

**Comment by lianattily** [comment]
fixed
