### ISSUE TITLE
Guitar Conversion Does Not Support Simple Hammer Ons

### ISSUE THREAD

**Issue by PBaciu** [alborzdev/2311-Project#30]
Reporter: Patrick Alexander Baciu
Email: baciupat@my.yorku.ca
Platform: Windows 10

Name:
Guitar Conversion Does Not Support Simple Hammer Ons

Description:
Hammer ons are not functional.

Steps to Produce:
Start the application.
Paste in this sample guitar tab.
|-----------0h1---|-0---------------|  
|---------0-------|-0---------------|  
|-------1-------1-|-1---------------|    
|-----2-----------|-2---------------|  
|---2-------------|-2---------------|  
|-0---------------|-0---------------|  

Export
Import file into musicxml editor.

Expected result:
Hammer ons are registered in output.

Actual Result:
Hammer ons not registered in output. [screenshot1]

Input Used:
|-----------0h1---|-0---------------|  
|---------0-------|-0---------------|  
|-------1-------1-|-1---------------|    
|-----2-----------|-2---------------|  
|---2-------------|-2---------------|  
|-0---------------|-0---------------|  

Priority:
High

Status:

![image](https://user-images.githubusercontent.com/77293069/112356951-7677fe80-8ca5-11eb-905b-044d4d4628ff.png)

Ready for development

Screenshots:

**Comment by lianattily** [comment]
works!
