### ISSUE TITLE
Ctrl + x doesn't close program

### ISSUE THREAD

**Issue by Nicolae-Semionov** [alborzdev/2311-Project#33]
## Ctrl + x doesn't close program

Raised by: Nicolae Semionov, 216468498

commit: 6fb4d43

## Description
This is a very simple issue that was identified when trying different program shortcuts. The program states that ctrl + x should exit the program, but doesn't.

## Input & Result
Pressing ctrl + o opens file explorer as expected, but ctrl + x doesn't do anything
![Screenshot 2021-03-24 191938](https://user-images.githubusercontent.com/46364601/112396087-f1f1a400-8cd5-11eb-9c2d-0600cbb76e1c.png)

Priority: Low
This issue is not very important. Should be a quick fix.

**Comment by lianattily** [comment]
Feature omitted.
