### ISSUE TITLE
Error When Trying To Save Changes To A File

### ISSUE THREAD

**Issue by Sara-Araibi** [alborzdev/2311-Project#34]
**Reporter:** Sara Araibi, sara012@my.yorku.ca
**Product:** Tab2XML
**Platform:** Mac OS
**Priority:** High
**Severity:** Major

**Description:** When uploading a valid file ( [Guitar.txt](https://github.com/alborzdev/2311Project/files/6200945/Guitar.txt) ) and creating changes in the window displaying the content of the text file, the save button does not work accordingly. The save button does not work properly in a sense where it does not save the changes to the original file (the uploaded version) or does not create a new file to save these changes.
**Reproduction:** When making changes to the window displaying the content of the file, add a pop-up window where it will allow the user to save the changes into a new file or to the original file.
**Expected behaviour:** To save new changes in the window to either a new file or the original file.
**Actual Behaviour:** Does not save new changes in the window to any file.

**Screenshots:**
Original text file:
<img width="611" alt="Screen Shot 2021-03-24 at 7 19 40 PM" src="https://user-images.githubusercontent.com/46364512/112396062-e69e7880-8cd5-11eb-9320-e88e2598e9ac.png">

Original file uploaded:
<img width="1251" alt="Screen Shot 2021-03-24 at 7 22 20 PM" src="https://user-images.githubusercontent.com/46364512/112396365-5f053980-8cd6-11eb-9b12-6f63d7ac3be2.png">

Changes to the file:
<img width="1247" alt="Screen Shot 2021-03-24 at 7 24 06 PM" src="https://user-images.githubusercontent.com/46364512/112396429-852ad980-8cd6-11eb-94f9-05ac28c0e7ca.png">

Asking/telling user to save changes:

<img width="1248" alt="Screen Shot 2021-03-24 at 7 24 29 PM" src="https://user-images.githubusercontent.com/46364512/112396502-a25fa800-8cd6-11eb-945c-897e60a0e2b9.png">

New changes not saved:
<img width="621" alt="Screen Shot 2021-03-24 at 7 26 00 PM" src="https://user-images.githubusercontent.com/46364512/112396612-d5a23700-8cd6-11eb-81f3-8cbc51cb8bf4.png">
<img width="434" alt="Screen Shot 2021-03-24 at 7 26 21 PM" src="https://user-images.githubusercontent.com/46364512/112396626-db981800-8cd6-11eb-843b-48f48a299d58.png">

**Comment by lianattily** [comment]
fixed.
