### ISSUE TITLE
Bug: 3/4 Timing does not work

### ISSUE THREAD

**Issue by AndyLin-1** [alborzdev/2311-Project#35]
### Name:
when converting a tablature and selecting 3/4 time signature the conversion has an error

### Description:

When pasting a tab into the editor, and then selecting the 3/4 time for time signature and then hitting export, the program converts the tablature but the end result is not what should be outputted. The program removes a whole part of the tablature and keeps the rest the same as the 4/4 time signature:

### Input:

![image](https://user-images.githubusercontent.com/56489106/112398260-2d8e6d00-8cda-11eb-9f49-0728498df349.png)

With 3/4 Time signature

### Actual Result:

![image](https://user-images.githubusercontent.com/56489106/112398317-4f87ef80-8cda-11eb-8ac0-54a74b655cb4.png)

###  Steps to recreate:
1. Paste the tablature above
2. Select 3/4 time signature
3. Export the music XML file

### Priority: 
medium

### Severity:

Priority for this is medium as most 3/4 4/4 are both common time signatures so if user wants to switch it the program should be able to convert it correctly, this should be ready when deploying the program

**Comment by lianattily** [comment]
fixed!
