### ISSUE TITLE
Error Message Is Still Displaying After The Error Has Been Fixed 

### ISSUE THREAD

**Issue by Sara-Araibi** [alborzdev/2311-Project#36]
**Reporter:** Sara Araibi, sara012@my.yorku.ca
**Product:** Tab2XML
**Platform:** Mac OS
**Priority:** High
**Severity:** Major

**Description:** When uploading an invalid file containing an invalid tablature, an error message is showed on the side of the application saying that there is a bad content and displaying the line of the error. But when correcting the error to make it a valid text file the error message on the side is still displayed.
**Reproduction:** When an error is identified, the application should tell the user that there is an error and at which line the error is occuring. Once the error is fixed the error message should go away and the application should display a message saying the text file is now valid.
**Expected behaviour:** Once the error is fixed, the error message on the side should be gone.
**Actual Behaviour:** The error message is still displaying even after the errors have been fixed.

**Screenshots:**
Screenshot of the error message in red, displaying where the error is and what the error is.
<img width="1213" alt="Screen Shot 2021-03-24 at 7 57 33 PM" src="https://user-images.githubusercontent.com/46364512/112398802-4d726080-8cdb-11eb-8561-f6bca7e02c52.png">

Screenshot of when the error is fixed but the error message is still displayed on the side.
<img width="1205" alt="Screen Shot 2021-03-24 at 7 57 44 PM" src="https://user-images.githubusercontent.com/46364512/112398953-ab06ad00-8cdb-11eb-9a6b-9df42fe6c50c.png">

**Comment by lianattily** [comment]
fixed!
