### ISSUE TITLE
Bug: No error messages when switching between instruments

### ISSUE THREAD

**Issue by AndyLin-1** [alborzdev/2311-Project#37]
### Name: 
When switching between instruments the error checker does not check after switching.

### Description: 
If I select drum, then paste a guitar tablature, then switch it back to guitar without changing the text in the editor, the program itself does not give an error message, and after exporting the converted file does not save after selecting a file name to save as.

### Input: Any Guitar Tablature that is unsupported (Formatting errors)
Example below:
![image](https://user-images.githubusercontent.com/56489106/112400159-1f425000-8cde-11eb-9b88-19be00556dc1.png)
The x3 is not supported by the guitar converter

### Expected Output: 
Music XML file for the guitar tablature or a error message 

### Actual Output: 
No output and no error message

### Steps to recreate:
1. Open converter
2. Select Drum as instrument
3. Paste the guitar tab that has formatting error
4. Switch the instrument back to guitar
5. click export
6. Choose name to save as and destination

File does not save

### Priority:
Medium

### Severity:
This has a medium priority as when users are using the converter they will probably be switching from instruments to instruments, and if the system does not recognize the error when a switching from one to another instrument unless they make an edit the user might be confused after clicking the export button.

**Comment by lianattily** [comment]
instrument detection feature added!
