### ISSUE TITLE
Bug: Editing the Tab in the textfield highlights the entire line

### ISSUE THREAD

**Issue by Saniac249** [alborzdev/2311-Project#39]
**Issue Title:** Unnecessary highlighting of the entire line when trying to edit

After opening the program, if the user inputs a tablature and tries toe edit it in the textfield, the entire line is highlighted making it hard for making changes.

**Version:**

Version 15 of Java SE Platform (* Java-15 as stated in User Manual)

**Platform:**

macOS Big Sur

**Steps to Reproduce:**

- Run the Program
- Click "Upload" and upload a tab (Screenshot 1)
- Click to the text field and press backspace on any line
- The entire line gets highlighted thus making it harder to make simultaneous changes to the tab (Screenshot 2)

**Expected:**

The expectation from the program would be to allow the user to edit the tab character by character making it more convenient.

**Actual:**

The program highlights the entire line making it harder for the user to make multiple changes and overall time consuming.

**Priority:**

Low - This is a small bug but does require proper inspection as to what is causing the bug. Very time consuming.

**Severity:**

Low - As it creates confusion among the users as they are unable to edit the file properly and causes time delay for users in hurry.

**Input Used:**

|-----------0-----|-0---------------|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|

**Screenshots:**

**Screenshot 1:** Shows he file uploaded to the text field 

<img width="1259" alt="Screen Shot 2021-03-25 at 6 05 03 AM" src="https://user-images.githubusercontent.com/75386358/112408673-aa990100-8d31-11eb-90a8-d49e5e553f86.png">

**Screenshot 2:** Shows the entire line being highlighted when trying to edit 1 character

<img width="1256" alt="Screen Shot 2021-03-25 at 6 05 12 AM" src="https://user-images.githubusercontent.com/75386358/112408692-b4226900-8d31-11eb-9b00-9e2303213309.png">

**Comment by lianattily** [comment]
fixed!
